# Configuration for golangci-lint
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet         # Reports suspicious constructs
    - errcheck      # Checks for unhandled errors
    - staticcheck   # A huge set of static analysis checks
    - unused        # Checks for unused code
    - ineffassign   # Checks for ineffectual assignments
    - revive        # Fast, configurable, modern replacement for golint
    - gocritic      # Provides checks for common errors and style issues
    - unconvert     # Checks for unnecessary type conversions
    - misspell      # Corrects common misspellings in comments
  
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
          - revive



formatters:
  enable:
   - goimports
  settings:
    goimports:
      local-prefixes: github.com/nicopolazzi/collector

