name: CI on Linux

on:
  push:
    branches:
      - main
    paths-ignore:
        - '**.md'
  pull_request:
    paths-ignore:
        - '**.md'

permissions:
  contents: read

env:
  GO_VERSION: '1.24'

jobs:
  golangci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{env.GO_VERSION}}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{env.GO_VERSION}}
          cache: false
      
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Run tests
        run: go test -v -race -covermode=atomic -coverprofile=coverage.txt ./internal/...

      - name: Build
        run: go build -v ./cmd/collector

  build:
    runs-on: ubuntu-24.04
    needs: [golangci, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./cmd/collector